# ======================================
#  Perfil DEV — PostgreSQL en Docker
# ======================================

spring.datasource.url=jdbc:postgresql://localhost:5432/cineclub
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=cineclub_user
spring.datasource.password=cineclub_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
