# ======================================
#  Configuración del backend de CineClub Salamanca
# ======================================

# Servidor
server.port=8080

spring.profiles.active=dev

# ---- JWT ----
# Cambia este secret por una cadena de al menos 32 caracteres en produccion
app.jwt.secret=cineclubsalamancasecretkey2026##supersecreto
app.jwt.expiration-ms=86400000

# ---- Registros ----
logging.level.com.cineclubsalamanca=DEBUG
