# ======================================
#  Perfil DEV — PostgreSQL en Docker
# ======================================

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:cineclub}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER:cineclub_user}
spring.datasource.password=${POSTGRES_PASSWORD:cineclub_pass}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
